name: Workflow A
on:
  push:
    branches: [ "main" ]
jobs:
  some_job:  
    runs-on: windows-latest
    steps:
      - name: Some Step 
        run: echo "Hello!"\

      - name: Some Step 
        run: |
            printf '{ 
              "prop_1": "Some value",  
              "prop_2": true
            }' >> context.json
      - uses: actions/upload-artifact@v4
        with:
          name: payroll-dlls
          path: ./*.json
