name: Workflow A
on:
  push:
    branches: [ "main" ]
jobs:
  some_job:  
    runs-on: windows-latest
    steps:
      - name: Some Step 
        run: echo "Hello!" >> hello.txt

      - name: Upload payroll DLLs as artifact
        uses: actions/upload-artifact@v4
        with:
         name: payroll-dlls
         path: "${{ github.workspace }}/*.txt"

      - name: print run_id
        run : echo "${{ github.run_id }}" 

      - name: Some Step 
        run: |
            printf '{ 
              "payroll-run-id": "${{ github.run_id }}" 
            }' >> context.json
      - uses: actions/upload-artifact@v4
        with:
          name: context.json
          path: ./
