name: Workflow 1
on:
#   push:
#     branches: [test]
  workflow_dispatch:
    
    
jobs:
  some_job:  
    runs-on: windows-latest
    steps:
      - name: Some Step
        run: echo "Hello! workflow1"