name: Workflow-3
on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["Workflow-2"]
    types:
      - completed
    
jobs:
  some_job:  
    runs-on: windows-latest
    steps:
      - name: Some Step 
        run: echo "Hello!"